// Generated by gencpp from file tum_alle_common_msgs/srvCostmap.msg
// DO NOT EDIT!


#ifndef TUM_ALLE_COMMON_MSGS_MESSAGE_SRVCOSTMAP_H
#define TUM_ALLE_COMMON_MSGS_MESSAGE_SRVCOSTMAP_H

#include <ros/service_traits.h>


#include <tum_alle_common_msgs/srvCostmapRequest.h>
#include <tum_alle_common_msgs/srvCostmapResponse.h>


namespace tum_alle_common_msgs
{

struct srvCostmap
{

typedef srvCostmapRequest Request;
typedef srvCostmapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct srvCostmap
} // namespace tum_alle_common_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tum_alle_common_msgs::srvCostmap > {
  static const char* value()
  {
    return "7d4bdfdbe811139a2c1fad39419d527f";
  }

  static const char* value(const ::tum_alle_common_msgs::srvCostmap&) { return value(); }
};

template<>
struct DataType< ::tum_alle_common_msgs::srvCostmap > {
  static const char* value()
  {
    return "tum_alle_common_msgs/srvCostmap";
  }

  static const char* value(const ::tum_alle_common_msgs::srvCostmap&) { return value(); }
};


// service_traits::MD5Sum< ::tum_alle_common_msgs::srvCostmapRequest> should match 
// service_traits::MD5Sum< ::tum_alle_common_msgs::srvCostmap > 
template<>
struct MD5Sum< ::tum_alle_common_msgs::srvCostmapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tum_alle_common_msgs::srvCostmap >::value();
  }
  static const char* value(const ::tum_alle_common_msgs::srvCostmapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tum_alle_common_msgs::srvCostmapRequest> should match 
// service_traits::DataType< ::tum_alle_common_msgs::srvCostmap > 
template<>
struct DataType< ::tum_alle_common_msgs::srvCostmapRequest>
{
  static const char* value()
  {
    return DataType< ::tum_alle_common_msgs::srvCostmap >::value();
  }
  static const char* value(const ::tum_alle_common_msgs::srvCostmapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tum_alle_common_msgs::srvCostmapResponse> should match 
// service_traits::MD5Sum< ::tum_alle_common_msgs::srvCostmap > 
template<>
struct MD5Sum< ::tum_alle_common_msgs::srvCostmapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tum_alle_common_msgs::srvCostmap >::value();
  }
  static const char* value(const ::tum_alle_common_msgs::srvCostmapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tum_alle_common_msgs::srvCostmapResponse> should match 
// service_traits::DataType< ::tum_alle_common_msgs::srvCostmap > 
template<>
struct DataType< ::tum_alle_common_msgs::srvCostmapResponse>
{
  static const char* value()
  {
    return DataType< ::tum_alle_common_msgs::srvCostmap >::value();
  }
  static const char* value(const ::tum_alle_common_msgs::srvCostmapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TUM_ALLE_COMMON_MSGS_MESSAGE_SRVCOSTMAP_H
