// Generated by gencpp from file tum_alle_common_msgs/srvClusterPerson.msg
// DO NOT EDIT!


#ifndef TUM_ALLE_COMMON_MSGS_MESSAGE_SRVCLUSTERPERSON_H
#define TUM_ALLE_COMMON_MSGS_MESSAGE_SRVCLUSTERPERSON_H

#include <ros/service_traits.h>


#include <tum_alle_common_msgs/srvClusterPersonRequest.h>
#include <tum_alle_common_msgs/srvClusterPersonResponse.h>


namespace tum_alle_common_msgs
{

struct srvClusterPerson
{

typedef srvClusterPersonRequest Request;
typedef srvClusterPersonResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct srvClusterPerson
} // namespace tum_alle_common_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tum_alle_common_msgs::srvClusterPerson > {
  static const char* value()
  {
    return "027335564df029fa5d68697960ac5d29";
  }

  static const char* value(const ::tum_alle_common_msgs::srvClusterPerson&) { return value(); }
};

template<>
struct DataType< ::tum_alle_common_msgs::srvClusterPerson > {
  static const char* value()
  {
    return "tum_alle_common_msgs/srvClusterPerson";
  }

  static const char* value(const ::tum_alle_common_msgs::srvClusterPerson&) { return value(); }
};


// service_traits::MD5Sum< ::tum_alle_common_msgs::srvClusterPersonRequest> should match 
// service_traits::MD5Sum< ::tum_alle_common_msgs::srvClusterPerson > 
template<>
struct MD5Sum< ::tum_alle_common_msgs::srvClusterPersonRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tum_alle_common_msgs::srvClusterPerson >::value();
  }
  static const char* value(const ::tum_alle_common_msgs::srvClusterPersonRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tum_alle_common_msgs::srvClusterPersonRequest> should match 
// service_traits::DataType< ::tum_alle_common_msgs::srvClusterPerson > 
template<>
struct DataType< ::tum_alle_common_msgs::srvClusterPersonRequest>
{
  static const char* value()
  {
    return DataType< ::tum_alle_common_msgs::srvClusterPerson >::value();
  }
  static const char* value(const ::tum_alle_common_msgs::srvClusterPersonRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tum_alle_common_msgs::srvClusterPersonResponse> should match 
// service_traits::MD5Sum< ::tum_alle_common_msgs::srvClusterPerson > 
template<>
struct MD5Sum< ::tum_alle_common_msgs::srvClusterPersonResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tum_alle_common_msgs::srvClusterPerson >::value();
  }
  static const char* value(const ::tum_alle_common_msgs::srvClusterPersonResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tum_alle_common_msgs::srvClusterPersonResponse> should match 
// service_traits::DataType< ::tum_alle_common_msgs::srvClusterPerson > 
template<>
struct DataType< ::tum_alle_common_msgs::srvClusterPersonResponse>
{
  static const char* value()
  {
    return DataType< ::tum_alle_common_msgs::srvClusterPerson >::value();
  }
  static const char* value(const ::tum_alle_common_msgs::srvClusterPersonResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TUM_ALLE_COMMON_MSGS_MESSAGE_SRVCLUSTERPERSON_H
