// Generated by gencpp from file tum_alle_common_msgs/srvCupboardDoorResponse.msg
// DO NOT EDIT!


#ifndef TUM_ALLE_COMMON_MSGS_MESSAGE_SRVCUPBOARDDOORRESPONSE_H
#define TUM_ALLE_COMMON_MSGS_MESSAGE_SRVCUPBOARDDOORRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tum_alle_common_msgs
{
template <class ContainerAllocator>
struct srvCupboardDoorResponse_
{
  typedef srvCupboardDoorResponse_<ContainerAllocator> Type;

  srvCupboardDoorResponse_()
    : position()
    , door_detected(false)  {
    }
  srvCupboardDoorResponse_(const ContainerAllocator& _alloc)
    : position(_alloc)
    , door_detected(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _position_type;
  _position_type position;

   typedef uint8_t _door_detected_type;
  _door_detected_type door_detected;





  typedef boost::shared_ptr< ::tum_alle_common_msgs::srvCupboardDoorResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tum_alle_common_msgs::srvCupboardDoorResponse_<ContainerAllocator> const> ConstPtr;

}; // struct srvCupboardDoorResponse_

typedef ::tum_alle_common_msgs::srvCupboardDoorResponse_<std::allocator<void> > srvCupboardDoorResponse;

typedef boost::shared_ptr< ::tum_alle_common_msgs::srvCupboardDoorResponse > srvCupboardDoorResponsePtr;
typedef boost::shared_ptr< ::tum_alle_common_msgs::srvCupboardDoorResponse const> srvCupboardDoorResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tum_alle_common_msgs::srvCupboardDoorResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tum_alle_common_msgs::srvCupboardDoorResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tum_alle_common_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'tum_alle_common_msgs': ['/home/atHomeSS18/God-Watcher/workspace/Finalproject/src/tum_alle_common_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tum_alle_common_msgs::srvCupboardDoorResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tum_alle_common_msgs::srvCupboardDoorResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tum_alle_common_msgs::srvCupboardDoorResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tum_alle_common_msgs::srvCupboardDoorResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tum_alle_common_msgs::srvCupboardDoorResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tum_alle_common_msgs::srvCupboardDoorResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tum_alle_common_msgs::srvCupboardDoorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "483fff4263a46b56a461e1ddc69726c9";
  }

  static const char* value(const ::tum_alle_common_msgs::srvCupboardDoorResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x483fff4263a46b56ULL;
  static const uint64_t static_value2 = 0xa461e1ddc69726c9ULL;
};

template<class ContainerAllocator>
struct DataType< ::tum_alle_common_msgs::srvCupboardDoorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tum_alle_common_msgs/srvCupboardDoorResponse";
  }

  static const char* value(const ::tum_alle_common_msgs::srvCupboardDoorResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tum_alle_common_msgs::srvCupboardDoorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string position\n\
bool   door_detected\n\
\n\
";
  }

  static const char* value(const ::tum_alle_common_msgs::srvCupboardDoorResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tum_alle_common_msgs::srvCupboardDoorResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.door_detected);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct srvCupboardDoorResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tum_alle_common_msgs::srvCupboardDoorResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tum_alle_common_msgs::srvCupboardDoorResponse_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.position);
    s << indent << "door_detected: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.door_detected);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUM_ALLE_COMMON_MSGS_MESSAGE_SRVCUPBOARDDOORRESPONSE_H
