// Generated by gencpp from file tum_alle_common_msgs/srvCupboardOrientation.msg
// DO NOT EDIT!


#ifndef TUM_ALLE_COMMON_MSGS_MESSAGE_SRVCUPBOARDORIENTATION_H
#define TUM_ALLE_COMMON_MSGS_MESSAGE_SRVCUPBOARDORIENTATION_H

#include <ros/service_traits.h>


#include <tum_alle_common_msgs/srvCupboardOrientationRequest.h>
#include <tum_alle_common_msgs/srvCupboardOrientationResponse.h>


namespace tum_alle_common_msgs
{

struct srvCupboardOrientation
{

typedef srvCupboardOrientationRequest Request;
typedef srvCupboardOrientationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct srvCupboardOrientation
} // namespace tum_alle_common_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tum_alle_common_msgs::srvCupboardOrientation > {
  static const char* value()
  {
    return "53c6fb80ff67f1c304b20833f46e6c0d";
  }

  static const char* value(const ::tum_alle_common_msgs::srvCupboardOrientation&) { return value(); }
};

template<>
struct DataType< ::tum_alle_common_msgs::srvCupboardOrientation > {
  static const char* value()
  {
    return "tum_alle_common_msgs/srvCupboardOrientation";
  }

  static const char* value(const ::tum_alle_common_msgs::srvCupboardOrientation&) { return value(); }
};


// service_traits::MD5Sum< ::tum_alle_common_msgs::srvCupboardOrientationRequest> should match 
// service_traits::MD5Sum< ::tum_alle_common_msgs::srvCupboardOrientation > 
template<>
struct MD5Sum< ::tum_alle_common_msgs::srvCupboardOrientationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tum_alle_common_msgs::srvCupboardOrientation >::value();
  }
  static const char* value(const ::tum_alle_common_msgs::srvCupboardOrientationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tum_alle_common_msgs::srvCupboardOrientationRequest> should match 
// service_traits::DataType< ::tum_alle_common_msgs::srvCupboardOrientation > 
template<>
struct DataType< ::tum_alle_common_msgs::srvCupboardOrientationRequest>
{
  static const char* value()
  {
    return DataType< ::tum_alle_common_msgs::srvCupboardOrientation >::value();
  }
  static const char* value(const ::tum_alle_common_msgs::srvCupboardOrientationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tum_alle_common_msgs::srvCupboardOrientationResponse> should match 
// service_traits::MD5Sum< ::tum_alle_common_msgs::srvCupboardOrientation > 
template<>
struct MD5Sum< ::tum_alle_common_msgs::srvCupboardOrientationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tum_alle_common_msgs::srvCupboardOrientation >::value();
  }
  static const char* value(const ::tum_alle_common_msgs::srvCupboardOrientationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tum_alle_common_msgs::srvCupboardOrientationResponse> should match 
// service_traits::DataType< ::tum_alle_common_msgs::srvCupboardOrientation > 
template<>
struct DataType< ::tum_alle_common_msgs::srvCupboardOrientationResponse>
{
  static const char* value()
  {
    return DataType< ::tum_alle_common_msgs::srvCupboardOrientation >::value();
  }
  static const char* value(const ::tum_alle_common_msgs::srvCupboardOrientationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TUM_ALLE_COMMON_MSGS_MESSAGE_SRVCUPBOARDORIENTATION_H
