// Generated by gencpp from file tum_alle_common_msgs/srvFreeSpace.msg
// DO NOT EDIT!


#ifndef TUM_ALLE_COMMON_MSGS_MESSAGE_SRVFREESPACE_H
#define TUM_ALLE_COMMON_MSGS_MESSAGE_SRVFREESPACE_H

#include <ros/service_traits.h>


#include <tum_alle_common_msgs/srvFreeSpaceRequest.h>
#include <tum_alle_common_msgs/srvFreeSpaceResponse.h>


namespace tum_alle_common_msgs
{

struct srvFreeSpace
{

typedef srvFreeSpaceRequest Request;
typedef srvFreeSpaceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct srvFreeSpace
} // namespace tum_alle_common_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tum_alle_common_msgs::srvFreeSpace > {
  static const char* value()
  {
    return "e7bbf846ac124617879d82f8cbf6f51d";
  }

  static const char* value(const ::tum_alle_common_msgs::srvFreeSpace&) { return value(); }
};

template<>
struct DataType< ::tum_alle_common_msgs::srvFreeSpace > {
  static const char* value()
  {
    return "tum_alle_common_msgs/srvFreeSpace";
  }

  static const char* value(const ::tum_alle_common_msgs::srvFreeSpace&) { return value(); }
};


// service_traits::MD5Sum< ::tum_alle_common_msgs::srvFreeSpaceRequest> should match 
// service_traits::MD5Sum< ::tum_alle_common_msgs::srvFreeSpace > 
template<>
struct MD5Sum< ::tum_alle_common_msgs::srvFreeSpaceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tum_alle_common_msgs::srvFreeSpace >::value();
  }
  static const char* value(const ::tum_alle_common_msgs::srvFreeSpaceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tum_alle_common_msgs::srvFreeSpaceRequest> should match 
// service_traits::DataType< ::tum_alle_common_msgs::srvFreeSpace > 
template<>
struct DataType< ::tum_alle_common_msgs::srvFreeSpaceRequest>
{
  static const char* value()
  {
    return DataType< ::tum_alle_common_msgs::srvFreeSpace >::value();
  }
  static const char* value(const ::tum_alle_common_msgs::srvFreeSpaceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tum_alle_common_msgs::srvFreeSpaceResponse> should match 
// service_traits::MD5Sum< ::tum_alle_common_msgs::srvFreeSpace > 
template<>
struct MD5Sum< ::tum_alle_common_msgs::srvFreeSpaceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tum_alle_common_msgs::srvFreeSpace >::value();
  }
  static const char* value(const ::tum_alle_common_msgs::srvFreeSpaceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tum_alle_common_msgs::srvFreeSpaceResponse> should match 
// service_traits::DataType< ::tum_alle_common_msgs::srvFreeSpace > 
template<>
struct DataType< ::tum_alle_common_msgs::srvFreeSpaceResponse>
{
  static const char* value()
  {
    return DataType< ::tum_alle_common_msgs::srvFreeSpace >::value();
  }
  static const char* value(const ::tum_alle_common_msgs::srvFreeSpaceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TUM_ALLE_COMMON_MSGS_MESSAGE_SRVFREESPACE_H
