// Generated by gencpp from file tum_alle_common_msgs/srvNavigation.msg
// DO NOT EDIT!


#ifndef TUM_ALLE_COMMON_MSGS_MESSAGE_SRVNAVIGATION_H
#define TUM_ALLE_COMMON_MSGS_MESSAGE_SRVNAVIGATION_H

#include <ros/service_traits.h>


#include <tum_alle_common_msgs/srvNavigationRequest.h>
#include <tum_alle_common_msgs/srvNavigationResponse.h>


namespace tum_alle_common_msgs
{

struct srvNavigation
{

typedef srvNavigationRequest Request;
typedef srvNavigationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct srvNavigation
} // namespace tum_alle_common_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tum_alle_common_msgs::srvNavigation > {
  static const char* value()
  {
    return "678835c49305ac0de54f01e826b6f3ff";
  }

  static const char* value(const ::tum_alle_common_msgs::srvNavigation&) { return value(); }
};

template<>
struct DataType< ::tum_alle_common_msgs::srvNavigation > {
  static const char* value()
  {
    return "tum_alle_common_msgs/srvNavigation";
  }

  static const char* value(const ::tum_alle_common_msgs::srvNavigation&) { return value(); }
};


// service_traits::MD5Sum< ::tum_alle_common_msgs::srvNavigationRequest> should match 
// service_traits::MD5Sum< ::tum_alle_common_msgs::srvNavigation > 
template<>
struct MD5Sum< ::tum_alle_common_msgs::srvNavigationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tum_alle_common_msgs::srvNavigation >::value();
  }
  static const char* value(const ::tum_alle_common_msgs::srvNavigationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tum_alle_common_msgs::srvNavigationRequest> should match 
// service_traits::DataType< ::tum_alle_common_msgs::srvNavigation > 
template<>
struct DataType< ::tum_alle_common_msgs::srvNavigationRequest>
{
  static const char* value()
  {
    return DataType< ::tum_alle_common_msgs::srvNavigation >::value();
  }
  static const char* value(const ::tum_alle_common_msgs::srvNavigationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tum_alle_common_msgs::srvNavigationResponse> should match 
// service_traits::MD5Sum< ::tum_alle_common_msgs::srvNavigation > 
template<>
struct MD5Sum< ::tum_alle_common_msgs::srvNavigationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tum_alle_common_msgs::srvNavigation >::value();
  }
  static const char* value(const ::tum_alle_common_msgs::srvNavigationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tum_alle_common_msgs::srvNavigationResponse> should match 
// service_traits::DataType< ::tum_alle_common_msgs::srvNavigation > 
template<>
struct DataType< ::tum_alle_common_msgs::srvNavigationResponse>
{
  static const char* value()
  {
    return DataType< ::tum_alle_common_msgs::srvNavigation >::value();
  }
  static const char* value(const ::tum_alle_common_msgs::srvNavigationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TUM_ALLE_COMMON_MSGS_MESSAGE_SRVNAVIGATION_H
