// Generated by gencpp from file tum_alle_common_msgs/srvObjectNavigation.msg
// DO NOT EDIT!


#ifndef TUM_ALLE_COMMON_MSGS_MESSAGE_SRVOBJECTNAVIGATION_H
#define TUM_ALLE_COMMON_MSGS_MESSAGE_SRVOBJECTNAVIGATION_H

#include <ros/service_traits.h>


#include <tum_alle_common_msgs/srvObjectNavigationRequest.h>
#include <tum_alle_common_msgs/srvObjectNavigationResponse.h>


namespace tum_alle_common_msgs
{

struct srvObjectNavigation
{

typedef srvObjectNavigationRequest Request;
typedef srvObjectNavigationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct srvObjectNavigation
} // namespace tum_alle_common_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tum_alle_common_msgs::srvObjectNavigation > {
  static const char* value()
  {
    return "2042acb7285e51f109192acb95ddf739";
  }

  static const char* value(const ::tum_alle_common_msgs::srvObjectNavigation&) { return value(); }
};

template<>
struct DataType< ::tum_alle_common_msgs::srvObjectNavigation > {
  static const char* value()
  {
    return "tum_alle_common_msgs/srvObjectNavigation";
  }

  static const char* value(const ::tum_alle_common_msgs::srvObjectNavigation&) { return value(); }
};


// service_traits::MD5Sum< ::tum_alle_common_msgs::srvObjectNavigationRequest> should match 
// service_traits::MD5Sum< ::tum_alle_common_msgs::srvObjectNavigation > 
template<>
struct MD5Sum< ::tum_alle_common_msgs::srvObjectNavigationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tum_alle_common_msgs::srvObjectNavigation >::value();
  }
  static const char* value(const ::tum_alle_common_msgs::srvObjectNavigationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tum_alle_common_msgs::srvObjectNavigationRequest> should match 
// service_traits::DataType< ::tum_alle_common_msgs::srvObjectNavigation > 
template<>
struct DataType< ::tum_alle_common_msgs::srvObjectNavigationRequest>
{
  static const char* value()
  {
    return DataType< ::tum_alle_common_msgs::srvObjectNavigation >::value();
  }
  static const char* value(const ::tum_alle_common_msgs::srvObjectNavigationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tum_alle_common_msgs::srvObjectNavigationResponse> should match 
// service_traits::MD5Sum< ::tum_alle_common_msgs::srvObjectNavigation > 
template<>
struct MD5Sum< ::tum_alle_common_msgs::srvObjectNavigationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tum_alle_common_msgs::srvObjectNavigation >::value();
  }
  static const char* value(const ::tum_alle_common_msgs::srvObjectNavigationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tum_alle_common_msgs::srvObjectNavigationResponse> should match 
// service_traits::DataType< ::tum_alle_common_msgs::srvObjectNavigation > 
template<>
struct DataType< ::tum_alle_common_msgs::srvObjectNavigationResponse>
{
  static const char* value()
  {
    return DataType< ::tum_alle_common_msgs::srvObjectNavigation >::value();
  }
  static const char* value(const ::tum_alle_common_msgs::srvObjectNavigationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TUM_ALLE_COMMON_MSGS_MESSAGE_SRVOBJECTNAVIGATION_H
