// Generated by gencpp from file tum_alle_athome_speech_msgs/msgTTSState.msg
// DO NOT EDIT!


#ifndef TUM_ALLE_ATHOME_SPEECH_MSGS_MESSAGE_MSGTTSSTATE_H
#define TUM_ALLE_ATHOME_SPEECH_MSGS_MESSAGE_MSGTTSSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tum_alle_athome_speech_msgs
{
template <class ContainerAllocator>
struct msgTTSState_
{
  typedef msgTTSState_<ContainerAllocator> Type;

  msgTTSState_()
    : state()  {
    }
  msgTTSState_(const ContainerAllocator& _alloc)
    : state(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::tum_alle_athome_speech_msgs::msgTTSState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tum_alle_athome_speech_msgs::msgTTSState_<ContainerAllocator> const> ConstPtr;

}; // struct msgTTSState_

typedef ::tum_alle_athome_speech_msgs::msgTTSState_<std::allocator<void> > msgTTSState;

typedef boost::shared_ptr< ::tum_alle_athome_speech_msgs::msgTTSState > msgTTSStatePtr;
typedef boost::shared_ptr< ::tum_alle_athome_speech_msgs::msgTTSState const> msgTTSStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tum_alle_athome_speech_msgs::msgTTSState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tum_alle_athome_speech_msgs::msgTTSState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tum_alle_athome_speech_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'tum_alle_athome_speech_msgs': ['/home/atHomeSS18/God-Watcher/workspace/Finalproject/src/speech/src/tum_alle_athome_speech/tum_alle_athome_speech_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tum_alle_athome_speech_msgs::msgTTSState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tum_alle_athome_speech_msgs::msgTTSState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tum_alle_athome_speech_msgs::msgTTSState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tum_alle_athome_speech_msgs::msgTTSState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tum_alle_athome_speech_msgs::msgTTSState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tum_alle_athome_speech_msgs::msgTTSState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tum_alle_athome_speech_msgs::msgTTSState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "af6d3a99f0fbeb66d3248fa4b3e675fb";
  }

  static const char* value(const ::tum_alle_athome_speech_msgs::msgTTSState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaf6d3a99f0fbeb66ULL;
  static const uint64_t static_value2 = 0xd3248fa4b3e675fbULL;
};

template<class ContainerAllocator>
struct DataType< ::tum_alle_athome_speech_msgs::msgTTSState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tum_alle_athome_speech_msgs/msgTTSState";
  }

  static const char* value(const ::tum_alle_athome_speech_msgs::msgTTSState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tum_alle_athome_speech_msgs::msgTTSState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string state\n\
";
  }

  static const char* value(const ::tum_alle_athome_speech_msgs::msgTTSState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tum_alle_athome_speech_msgs::msgTTSState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct msgTTSState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tum_alle_athome_speech_msgs::msgTTSState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tum_alle_athome_speech_msgs::msgTTSState_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUM_ALLE_ATHOME_SPEECH_MSGS_MESSAGE_MSGTTSSTATE_H
