// Generated by gencpp from file perception_msgs/send_flagsRequest.msg
// DO NOT EDIT!


#ifndef PERCEPTION_MSGS_MESSAGE_SEND_FLAGSREQUEST_H
#define PERCEPTION_MSGS_MESSAGE_SEND_FLAGSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace perception_msgs
{
template <class ContainerAllocator>
struct send_flagsRequest_
{
  typedef send_flagsRequest_<ContainerAllocator> Type;

  send_flagsRequest_()
    : flag(0)  {
    }
  send_flagsRequest_(const ContainerAllocator& _alloc)
    : flag(0)  {
  (void)_alloc;
    }



   typedef int64_t _flag_type;
  _flag_type flag;





  typedef boost::shared_ptr< ::perception_msgs::send_flagsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::perception_msgs::send_flagsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct send_flagsRequest_

typedef ::perception_msgs::send_flagsRequest_<std::allocator<void> > send_flagsRequest;

typedef boost::shared_ptr< ::perception_msgs::send_flagsRequest > send_flagsRequestPtr;
typedef boost::shared_ptr< ::perception_msgs::send_flagsRequest const> send_flagsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::perception_msgs::send_flagsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::perception_msgs::send_flagsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace perception_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'perception_msgs': ['/home/atHomeSS18/God-Watcher/workspace/tutorial5/src/perception_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::perception_msgs::send_flagsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception_msgs::send_flagsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_msgs::send_flagsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_msgs::send_flagsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_msgs::send_flagsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_msgs::send_flagsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::perception_msgs::send_flagsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "87ee459c4b4bcda4c5ae0619ce324ea2";
  }

  static const char* value(const ::perception_msgs::send_flagsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x87ee459c4b4bcda4ULL;
  static const uint64_t static_value2 = 0xc5ae0619ce324ea2ULL;
};

template<class ContainerAllocator>
struct DataType< ::perception_msgs::send_flagsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "perception_msgs/send_flagsRequest";
  }

  static const char* value(const ::perception_msgs::send_flagsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::perception_msgs::send_flagsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
int64 flag\n\
";
  }

  static const char* value(const ::perception_msgs::send_flagsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::perception_msgs::send_flagsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.flag);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct send_flagsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::perception_msgs::send_flagsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::perception_msgs::send_flagsRequest_<ContainerAllocator>& v)
  {
    s << indent << "flag: ";
    Printer<int64_t>::stream(s, indent + "  ", v.flag);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PERCEPTION_MSGS_MESSAGE_SEND_FLAGSREQUEST_H
