// Generated by gencpp from file perception_msgs/send_flagsResponse.msg
// DO NOT EDIT!


#ifndef PERCEPTION_MSGS_MESSAGE_SEND_FLAGSRESPONSE_H
#define PERCEPTION_MSGS_MESSAGE_SEND_FLAGSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace perception_msgs
{
template <class ContainerAllocator>
struct send_flagsResponse_
{
  typedef send_flagsResponse_<ContainerAllocator> Type;

  send_flagsResponse_()
    : reply(0)  {
    }
  send_flagsResponse_(const ContainerAllocator& _alloc)
    : reply(0)  {
  (void)_alloc;
    }



   typedef int64_t _reply_type;
  _reply_type reply;





  typedef boost::shared_ptr< ::perception_msgs::send_flagsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::perception_msgs::send_flagsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct send_flagsResponse_

typedef ::perception_msgs::send_flagsResponse_<std::allocator<void> > send_flagsResponse;

typedef boost::shared_ptr< ::perception_msgs::send_flagsResponse > send_flagsResponsePtr;
typedef boost::shared_ptr< ::perception_msgs::send_flagsResponse const> send_flagsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::perception_msgs::send_flagsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::perception_msgs::send_flagsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace perception_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'perception_msgs': ['/home/atHomeSS18/God-Watcher/workspace/tutorial5/src/perception_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::perception_msgs::send_flagsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception_msgs::send_flagsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_msgs::send_flagsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_msgs::send_flagsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_msgs::send_flagsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_msgs::send_flagsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::perception_msgs::send_flagsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "60413af40da7a072a76f2e1c4dc15e92";
  }

  static const char* value(const ::perception_msgs::send_flagsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x60413af40da7a072ULL;
  static const uint64_t static_value2 = 0xa76f2e1c4dc15e92ULL;
};

template<class ContainerAllocator>
struct DataType< ::perception_msgs::send_flagsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "perception_msgs/send_flagsResponse";
  }

  static const char* value(const ::perception_msgs::send_flagsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::perception_msgs::send_flagsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
int64 reply\n\
\n\
";
  }

  static const char* value(const ::perception_msgs::send_flagsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::perception_msgs::send_flagsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.reply);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct send_flagsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::perception_msgs::send_flagsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::perception_msgs::send_flagsResponse_<ContainerAllocator>& v)
  {
    s << indent << "reply: ";
    Printer<int64_t>::stream(s, indent + "  ", v.reply);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PERCEPTION_MSGS_MESSAGE_SEND_FLAGSRESPONSE_H
