(cl:defpackage manipulation-msg
  (:use )
  (:export
   "<PICKUPPOSEACTION>"
   "PICKUPPOSEACTION"
   "<PICKUPPOSEACTIONFEEDBACK>"
   "PICKUPPOSEACTIONFEEDBACK"
   "<PICKUPPOSEACTIONGOAL>"
   "PICKUPPOSEACTIONGOAL"
   "<PICKUPPOSEACTIONRESULT>"
   "PICKUPPOSEACTIONRESULT"
   "<PICKUPPOSEFEEDBACK>"
   "PICKUPPOSEFEEDBACK"
   "<PICKUPPOSEGOAL>"
   "PICKUPPOSEGOAL"
   "<PICKUPPOSERESULT>"
   "PICKUPPOSERESULT"
  ))

