(cl:defpackage all_msgs-srv
  (:use )
  (:export
   "SEND_BOX"
   "<SEND_BOX-REQUEST>"
   "SEND_BOX-REQUEST"
   "<SEND_BOX-RESPONSE>"
   "SEND_BOX-RESPONSE"
   "SEND_FLAGS"
   "<SEND_FLAGS-REQUEST>"
   "SEND_FLAGS-REQUEST"
   "<SEND_FLAGS-RESPONSE>"
   "SEND_FLAGS-RESPONSE"
   "SEND_POS"
   "<SEND_POS-REQUEST>"
   "SEND_POS-REQUEST"
   "<SEND_POS-RESPONSE>"
   "SEND_POS-RESPONSE"
   "SEND_POSE"
   "<SEND_POSE-REQUEST>"
   "SEND_POSE-REQUEST"
   "<SEND_POSE-RESPONSE>"
   "SEND_POSE-RESPONSE"
  ))

