// Generated by gencpp from file all_msgs/send_pose.msg
// DO NOT EDIT!


#ifndef ALL_MSGS_MESSAGE_SEND_POSE_H
#define ALL_MSGS_MESSAGE_SEND_POSE_H

#include <ros/service_traits.h>


#include <all_msgs/send_poseRequest.h>
#include <all_msgs/send_poseResponse.h>


namespace all_msgs
{

struct send_pose
{

typedef send_poseRequest Request;
typedef send_poseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct send_pose
} // namespace all_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::all_msgs::send_pose > {
  static const char* value()
  {
    return "054de5c78a71069d7eba0f4079e28d3a";
  }

  static const char* value(const ::all_msgs::send_pose&) { return value(); }
};

template<>
struct DataType< ::all_msgs::send_pose > {
  static const char* value()
  {
    return "all_msgs/send_pose";
  }

  static const char* value(const ::all_msgs::send_pose&) { return value(); }
};


// service_traits::MD5Sum< ::all_msgs::send_poseRequest> should match 
// service_traits::MD5Sum< ::all_msgs::send_pose > 
template<>
struct MD5Sum< ::all_msgs::send_poseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::all_msgs::send_pose >::value();
  }
  static const char* value(const ::all_msgs::send_poseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::all_msgs::send_poseRequest> should match 
// service_traits::DataType< ::all_msgs::send_pose > 
template<>
struct DataType< ::all_msgs::send_poseRequest>
{
  static const char* value()
  {
    return DataType< ::all_msgs::send_pose >::value();
  }
  static const char* value(const ::all_msgs::send_poseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::all_msgs::send_poseResponse> should match 
// service_traits::MD5Sum< ::all_msgs::send_pose > 
template<>
struct MD5Sum< ::all_msgs::send_poseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::all_msgs::send_pose >::value();
  }
  static const char* value(const ::all_msgs::send_poseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::all_msgs::send_poseResponse> should match 
// service_traits::DataType< ::all_msgs::send_pose > 
template<>
struct DataType< ::all_msgs::send_poseResponse>
{
  static const char* value()
  {
    return DataType< ::all_msgs::send_pose >::value();
  }
  static const char* value(const ::all_msgs::send_poseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ALL_MSGS_MESSAGE_SEND_POSE_H
