// Generated by gencpp from file all_msgs/send_flags.msg
// DO NOT EDIT!


#ifndef ALL_MSGS_MESSAGE_SEND_FLAGS_H
#define ALL_MSGS_MESSAGE_SEND_FLAGS_H

#include <ros/service_traits.h>


#include <all_msgs/send_flagsRequest.h>
#include <all_msgs/send_flagsResponse.h>


namespace all_msgs
{

struct send_flags
{

typedef send_flagsRequest Request;
typedef send_flagsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct send_flags
} // namespace all_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::all_msgs::send_flags > {
  static const char* value()
  {
    return "020bdbc33a7ee6b93f149ccfbb819f7f";
  }

  static const char* value(const ::all_msgs::send_flags&) { return value(); }
};

template<>
struct DataType< ::all_msgs::send_flags > {
  static const char* value()
  {
    return "all_msgs/send_flags";
  }

  static const char* value(const ::all_msgs::send_flags&) { return value(); }
};


// service_traits::MD5Sum< ::all_msgs::send_flagsRequest> should match 
// service_traits::MD5Sum< ::all_msgs::send_flags > 
template<>
struct MD5Sum< ::all_msgs::send_flagsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::all_msgs::send_flags >::value();
  }
  static const char* value(const ::all_msgs::send_flagsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::all_msgs::send_flagsRequest> should match 
// service_traits::DataType< ::all_msgs::send_flags > 
template<>
struct DataType< ::all_msgs::send_flagsRequest>
{
  static const char* value()
  {
    return DataType< ::all_msgs::send_flags >::value();
  }
  static const char* value(const ::all_msgs::send_flagsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::all_msgs::send_flagsResponse> should match 
// service_traits::MD5Sum< ::all_msgs::send_flags > 
template<>
struct MD5Sum< ::all_msgs::send_flagsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::all_msgs::send_flags >::value();
  }
  static const char* value(const ::all_msgs::send_flagsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::all_msgs::send_flagsResponse> should match 
// service_traits::DataType< ::all_msgs::send_flags > 
template<>
struct DataType< ::all_msgs::send_flagsResponse>
{
  static const char* value()
  {
    return DataType< ::all_msgs::send_flags >::value();
  }
  static const char* value(const ::all_msgs::send_flagsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ALL_MSGS_MESSAGE_SEND_FLAGS_H
