// Generated by gencpp from file all_msgs/send_pos.msg
// DO NOT EDIT!


#ifndef ALL_MSGS_MESSAGE_SEND_POS_H
#define ALL_MSGS_MESSAGE_SEND_POS_H

#include <ros/service_traits.h>


#include <all_msgs/send_posRequest.h>
#include <all_msgs/send_posResponse.h>


namespace all_msgs
{

struct send_pos
{

typedef send_posRequest Request;
typedef send_posResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct send_pos
} // namespace all_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::all_msgs::send_pos > {
  static const char* value()
  {
    return "0937dcad83c5429e3efaf62274855790";
  }

  static const char* value(const ::all_msgs::send_pos&) { return value(); }
};

template<>
struct DataType< ::all_msgs::send_pos > {
  static const char* value()
  {
    return "all_msgs/send_pos";
  }

  static const char* value(const ::all_msgs::send_pos&) { return value(); }
};


// service_traits::MD5Sum< ::all_msgs::send_posRequest> should match 
// service_traits::MD5Sum< ::all_msgs::send_pos > 
template<>
struct MD5Sum< ::all_msgs::send_posRequest>
{
  static const char* value()
  {
    return MD5Sum< ::all_msgs::send_pos >::value();
  }
  static const char* value(const ::all_msgs::send_posRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::all_msgs::send_posRequest> should match 
// service_traits::DataType< ::all_msgs::send_pos > 
template<>
struct DataType< ::all_msgs::send_posRequest>
{
  static const char* value()
  {
    return DataType< ::all_msgs::send_pos >::value();
  }
  static const char* value(const ::all_msgs::send_posRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::all_msgs::send_posResponse> should match 
// service_traits::MD5Sum< ::all_msgs::send_pos > 
template<>
struct MD5Sum< ::all_msgs::send_posResponse>
{
  static const char* value()
  {
    return MD5Sum< ::all_msgs::send_pos >::value();
  }
  static const char* value(const ::all_msgs::send_posResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::all_msgs::send_posResponse> should match 
// service_traits::DataType< ::all_msgs::send_pos > 
template<>
struct DataType< ::all_msgs::send_posResponse>
{
  static const char* value()
  {
    return DataType< ::all_msgs::send_pos >::value();
  }
  static const char* value(const ::all_msgs::send_posResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ALL_MSGS_MESSAGE_SEND_POS_H
