// Generated by gencpp from file all_msgs/send_boxRequest.msg
// DO NOT EDIT!


#ifndef ALL_MSGS_MESSAGE_SEND_BOXREQUEST_H
#define ALL_MSGS_MESSAGE_SEND_BOXREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace all_msgs
{
template <class ContainerAllocator>
struct send_boxRequest_
{
  typedef send_boxRequest_<ContainerAllocator> Type;

  send_boxRequest_()
    : id()
    , x(0)
    , y(0)
    , height(0)
    , width(0)  {
    }
  send_boxRequest_(const ContainerAllocator& _alloc)
    : id(_alloc)
    , x(0)
    , y(0)
    , height(0)
    , width(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _id_type;
  _id_type id;

   typedef int32_t _x_type;
  _x_type x;

   typedef int32_t _y_type;
  _y_type y;

   typedef int32_t _height_type;
  _height_type height;

   typedef int32_t _width_type;
  _width_type width;





  typedef boost::shared_ptr< ::all_msgs::send_boxRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::all_msgs::send_boxRequest_<ContainerAllocator> const> ConstPtr;

}; // struct send_boxRequest_

typedef ::all_msgs::send_boxRequest_<std::allocator<void> > send_boxRequest;

typedef boost::shared_ptr< ::all_msgs::send_boxRequest > send_boxRequestPtr;
typedef boost::shared_ptr< ::all_msgs::send_boxRequest const> send_boxRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::all_msgs::send_boxRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::all_msgs::send_boxRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace all_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'all_msgs': ['/home/atHomeSS18/God-Watcher/workspace/Finalproject/src/all_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::all_msgs::send_boxRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::all_msgs::send_boxRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::all_msgs::send_boxRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::all_msgs::send_boxRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::all_msgs::send_boxRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::all_msgs::send_boxRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::all_msgs::send_boxRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "05e347a088db9063d000a572a0b71762";
  }

  static const char* value(const ::all_msgs::send_boxRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x05e347a088db9063ULL;
  static const uint64_t static_value2 = 0xd000a572a0b71762ULL;
};

template<class ContainerAllocator>
struct DataType< ::all_msgs::send_boxRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "all_msgs/send_boxRequest";
  }

  static const char* value(const ::all_msgs::send_boxRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::all_msgs::send_boxRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string id\n\
int32 x\n\
int32 y\n\
int32 height\n\
int32 width\n\
";
  }

  static const char* value(const ::all_msgs::send_boxRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::all_msgs::send_boxRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.height);
      stream.next(m.width);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct send_boxRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::all_msgs::send_boxRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::all_msgs::send_boxRequest_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.id);
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y);
    s << indent << "height: ";
    Printer<int32_t>::stream(s, indent + "  ", v.height);
    s << indent << "width: ";
    Printer<int32_t>::stream(s, indent + "  ", v.width);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALL_MSGS_MESSAGE_SEND_BOXREQUEST_H
