(cl:defpackage tum_alle_athome_speech_msgs-srv
  (:use )
  (:export
   "SRVGENERATEANSWER"
   "<SRVGENERATEANSWER-REQUEST>"
   "SRVGENERATEANSWER-REQUEST"
   "<SRVGENERATEANSWER-RESPONSE>"
   "SRVGENERATEANSWER-RESPONSE"
   "SRVQUESTION"
   "<SRVQUESTION-REQUEST>"
   "SRVQUESTION-REQUEST"
   "<SRVQUESTION-RESPONSE>"
   "SRVQUESTION-RESPONSE"
   "SRVTTS"
   "<SRVTTS-REQUEST>"
   "SRVTTS-REQUEST"
   "<SRVTTS-RESPONSE>"
   "SRVTTS-RESPONSE"
  ))

