// Generated by gencpp from file manipulation/PickUpPoseResult.msg
// DO NOT EDIT!


#ifndef MANIPULATION_MESSAGE_PICKUPPOSERESULT_H
#define MANIPULATION_MESSAGE_PICKUPPOSERESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace manipulation
{
template <class ContainerAllocator>
struct PickUpPoseResult_
{
  typedef PickUpPoseResult_<ContainerAllocator> Type;

  PickUpPoseResult_()
    : error_code(0)  {
    }
  PickUpPoseResult_(const ContainerAllocator& _alloc)
    : error_code(0)  {
  (void)_alloc;
    }



   typedef int32_t _error_code_type;
  _error_code_type error_code;





  typedef boost::shared_ptr< ::manipulation::PickUpPoseResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::manipulation::PickUpPoseResult_<ContainerAllocator> const> ConstPtr;

}; // struct PickUpPoseResult_

typedef ::manipulation::PickUpPoseResult_<std::allocator<void> > PickUpPoseResult;

typedef boost::shared_ptr< ::manipulation::PickUpPoseResult > PickUpPoseResultPtr;
typedef boost::shared_ptr< ::manipulation::PickUpPoseResult const> PickUpPoseResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::manipulation::PickUpPoseResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::manipulation::PickUpPoseResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace manipulation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'manipulation': ['/home/atHomeSS18/God-Watcher/workspace/Finalproject/devel/share/manipulation/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::manipulation::PickUpPoseResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manipulation::PickUpPoseResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::manipulation::PickUpPoseResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::manipulation::PickUpPoseResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manipulation::PickUpPoseResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manipulation::PickUpPoseResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::manipulation::PickUpPoseResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ea324a22c787839f822b9a025bc2c6fe";
  }

  static const char* value(const ::manipulation::PickUpPoseResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xea324a22c787839fULL;
  static const uint64_t static_value2 = 0x822b9a025bc2c6feULL;
};

template<class ContainerAllocator>
struct DataType< ::manipulation::PickUpPoseResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "manipulation/PickUpPoseResult";
  }

  static const char* value(const ::manipulation::PickUpPoseResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::manipulation::PickUpPoseResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#result definition\n\
# Comes from moveit_msgs/MoveItErrorCodes\n\
int32 error_code\n\
";
  }

  static const char* value(const ::manipulation::PickUpPoseResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::manipulation::PickUpPoseResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.error_code);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PickUpPoseResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::manipulation::PickUpPoseResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::manipulation::PickUpPoseResult_<ContainerAllocator>& v)
  {
    s << indent << "error_code: ";
    Printer<int32_t>::stream(s, indent + "  ", v.error_code);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MANIPULATION_MESSAGE_PICKUPPOSERESULT_H
