(cl:in-package all_msgs-msg)
(cl:export '(ID-VAL
          ID
          WORLD_POSE-VAL
          WORLD_POSE
          CAM_POSE-VAL
          CAM_POSE
          HEADING-VAL
          HEADING
          VELOCITY-VAL
          VELOCITY
          WIDTH-VAL
          WIDTH
          LENGTH-VAL
          LENGTH
          SEMANTIC_CONFIDENCE-VAL
          SEMANTIC_CONFIDENCE
          SEMANTIC_NAME-VAL
          SEMANTIC_NAME
          SEMANTIC_ID-VAL
          SEMANTIC_ID
          R-VAL
          R
          G-VAL
          G
          B-VAL
          B
          IS_TRACK-VAL
          IS_TRACK
          IS_TARGET-VAL
          IS_TARGET
))