(cl:defpackage tum_alle_common_msgs-msg
  (:use )
  (:export
   "<RECT>"
   "RECT"
   "<MSG2DPREDICTION>"
   "MSG2DPREDICTION"
   "<MSG2DRECOGNITION>"
   "MSG2DRECOGNITION"
   "<MSG3DPREDICTION>"
   "MSG3DPREDICTION"
   "<MSG3DRECOGNITION>"
   "MSG3DRECOGNITION"
   "<MSG3DTRACKING>"
   "MSG3DTRACKING"
   "<MSGCATEGORISEDSPEECH>"
   "MSGCATEGORISEDSPEECH"
   "<MSGFREESPACE>"
   "MSGFREESPACE"
   "<MSGGRASPINFO>"
   "MSGGRASPINFO"
   "<MSGHOTWORDCOMMAND>"
   "MSGHOTWORDCOMMAND"
   "<MSGREGIONOFINTEREST3D>"
   "MSGREGIONOFINTEREST3D"
   "<POINT3D>"
   "POINT3D"
  ))

