// Generated by gencpp from file tum_alle_common_msgs/srvControlTracker.msg
// DO NOT EDIT!


#ifndef TUM_ALLE_COMMON_MSGS_MESSAGE_SRVCONTROLTRACKER_H
#define TUM_ALLE_COMMON_MSGS_MESSAGE_SRVCONTROLTRACKER_H

#include <ros/service_traits.h>


#include <tum_alle_common_msgs/srvControlTrackerRequest.h>
#include <tum_alle_common_msgs/srvControlTrackerResponse.h>


namespace tum_alle_common_msgs
{

struct srvControlTracker
{

typedef srvControlTrackerRequest Request;
typedef srvControlTrackerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct srvControlTracker
} // namespace tum_alle_common_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tum_alle_common_msgs::srvControlTracker > {
  static const char* value()
  {
    return "031d24522d462b2314fd1b6270670dd2";
  }

  static const char* value(const ::tum_alle_common_msgs::srvControlTracker&) { return value(); }
};

template<>
struct DataType< ::tum_alle_common_msgs::srvControlTracker > {
  static const char* value()
  {
    return "tum_alle_common_msgs/srvControlTracker";
  }

  static const char* value(const ::tum_alle_common_msgs::srvControlTracker&) { return value(); }
};


// service_traits::MD5Sum< ::tum_alle_common_msgs::srvControlTrackerRequest> should match 
// service_traits::MD5Sum< ::tum_alle_common_msgs::srvControlTracker > 
template<>
struct MD5Sum< ::tum_alle_common_msgs::srvControlTrackerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tum_alle_common_msgs::srvControlTracker >::value();
  }
  static const char* value(const ::tum_alle_common_msgs::srvControlTrackerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tum_alle_common_msgs::srvControlTrackerRequest> should match 
// service_traits::DataType< ::tum_alle_common_msgs::srvControlTracker > 
template<>
struct DataType< ::tum_alle_common_msgs::srvControlTrackerRequest>
{
  static const char* value()
  {
    return DataType< ::tum_alle_common_msgs::srvControlTracker >::value();
  }
  static const char* value(const ::tum_alle_common_msgs::srvControlTrackerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tum_alle_common_msgs::srvControlTrackerResponse> should match 
// service_traits::MD5Sum< ::tum_alle_common_msgs::srvControlTracker > 
template<>
struct MD5Sum< ::tum_alle_common_msgs::srvControlTrackerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tum_alle_common_msgs::srvControlTracker >::value();
  }
  static const char* value(const ::tum_alle_common_msgs::srvControlTrackerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tum_alle_common_msgs::srvControlTrackerResponse> should match 
// service_traits::DataType< ::tum_alle_common_msgs::srvControlTracker > 
template<>
struct DataType< ::tum_alle_common_msgs::srvControlTrackerResponse>
{
  static const char* value()
  {
    return DataType< ::tum_alle_common_msgs::srvControlTracker >::value();
  }
  static const char* value(const ::tum_alle_common_msgs::srvControlTrackerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TUM_ALLE_COMMON_MSGS_MESSAGE_SRVCONTROLTRACKER_H
