// Generated by gencpp from file tum_alle_common_msgs/srvExtractProperty.msg
// DO NOT EDIT!


#ifndef TUM_ALLE_COMMON_MSGS_MESSAGE_SRVEXTRACTPROPERTY_H
#define TUM_ALLE_COMMON_MSGS_MESSAGE_SRVEXTRACTPROPERTY_H

#include <ros/service_traits.h>


#include <tum_alle_common_msgs/srvExtractPropertyRequest.h>
#include <tum_alle_common_msgs/srvExtractPropertyResponse.h>


namespace tum_alle_common_msgs
{

struct srvExtractProperty
{

typedef srvExtractPropertyRequest Request;
typedef srvExtractPropertyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct srvExtractProperty
} // namespace tum_alle_common_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tum_alle_common_msgs::srvExtractProperty > {
  static const char* value()
  {
    return "b253553970eafd667f42fcf9d6384784";
  }

  static const char* value(const ::tum_alle_common_msgs::srvExtractProperty&) { return value(); }
};

template<>
struct DataType< ::tum_alle_common_msgs::srvExtractProperty > {
  static const char* value()
  {
    return "tum_alle_common_msgs/srvExtractProperty";
  }

  static const char* value(const ::tum_alle_common_msgs::srvExtractProperty&) { return value(); }
};


// service_traits::MD5Sum< ::tum_alle_common_msgs::srvExtractPropertyRequest> should match 
// service_traits::MD5Sum< ::tum_alle_common_msgs::srvExtractProperty > 
template<>
struct MD5Sum< ::tum_alle_common_msgs::srvExtractPropertyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tum_alle_common_msgs::srvExtractProperty >::value();
  }
  static const char* value(const ::tum_alle_common_msgs::srvExtractPropertyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tum_alle_common_msgs::srvExtractPropertyRequest> should match 
// service_traits::DataType< ::tum_alle_common_msgs::srvExtractProperty > 
template<>
struct DataType< ::tum_alle_common_msgs::srvExtractPropertyRequest>
{
  static const char* value()
  {
    return DataType< ::tum_alle_common_msgs::srvExtractProperty >::value();
  }
  static const char* value(const ::tum_alle_common_msgs::srvExtractPropertyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tum_alle_common_msgs::srvExtractPropertyResponse> should match 
// service_traits::MD5Sum< ::tum_alle_common_msgs::srvExtractProperty > 
template<>
struct MD5Sum< ::tum_alle_common_msgs::srvExtractPropertyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tum_alle_common_msgs::srvExtractProperty >::value();
  }
  static const char* value(const ::tum_alle_common_msgs::srvExtractPropertyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tum_alle_common_msgs::srvExtractPropertyResponse> should match 
// service_traits::DataType< ::tum_alle_common_msgs::srvExtractProperty > 
template<>
struct DataType< ::tum_alle_common_msgs::srvExtractPropertyResponse>
{
  static const char* value()
  {
    return DataType< ::tum_alle_common_msgs::srvExtractProperty >::value();
  }
  static const char* value(const ::tum_alle_common_msgs::srvExtractPropertyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TUM_ALLE_COMMON_MSGS_MESSAGE_SRVEXTRACTPROPERTY_H
