// Generated by gencpp from file tum_alle_common_msgs/srvInferFromList.msg
// DO NOT EDIT!


#ifndef TUM_ALLE_COMMON_MSGS_MESSAGE_SRVINFERFROMLIST_H
#define TUM_ALLE_COMMON_MSGS_MESSAGE_SRVINFERFROMLIST_H

#include <ros/service_traits.h>


#include <tum_alle_common_msgs/srvInferFromListRequest.h>
#include <tum_alle_common_msgs/srvInferFromListResponse.h>


namespace tum_alle_common_msgs
{

struct srvInferFromList
{

typedef srvInferFromListRequest Request;
typedef srvInferFromListResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct srvInferFromList
} // namespace tum_alle_common_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tum_alle_common_msgs::srvInferFromList > {
  static const char* value()
  {
    return "ba1dfc2541572858b8492a33b42bd13b";
  }

  static const char* value(const ::tum_alle_common_msgs::srvInferFromList&) { return value(); }
};

template<>
struct DataType< ::tum_alle_common_msgs::srvInferFromList > {
  static const char* value()
  {
    return "tum_alle_common_msgs/srvInferFromList";
  }

  static const char* value(const ::tum_alle_common_msgs::srvInferFromList&) { return value(); }
};


// service_traits::MD5Sum< ::tum_alle_common_msgs::srvInferFromListRequest> should match 
// service_traits::MD5Sum< ::tum_alle_common_msgs::srvInferFromList > 
template<>
struct MD5Sum< ::tum_alle_common_msgs::srvInferFromListRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tum_alle_common_msgs::srvInferFromList >::value();
  }
  static const char* value(const ::tum_alle_common_msgs::srvInferFromListRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tum_alle_common_msgs::srvInferFromListRequest> should match 
// service_traits::DataType< ::tum_alle_common_msgs::srvInferFromList > 
template<>
struct DataType< ::tum_alle_common_msgs::srvInferFromListRequest>
{
  static const char* value()
  {
    return DataType< ::tum_alle_common_msgs::srvInferFromList >::value();
  }
  static const char* value(const ::tum_alle_common_msgs::srvInferFromListRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tum_alle_common_msgs::srvInferFromListResponse> should match 
// service_traits::MD5Sum< ::tum_alle_common_msgs::srvInferFromList > 
template<>
struct MD5Sum< ::tum_alle_common_msgs::srvInferFromListResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tum_alle_common_msgs::srvInferFromList >::value();
  }
  static const char* value(const ::tum_alle_common_msgs::srvInferFromListResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tum_alle_common_msgs::srvInferFromListResponse> should match 
// service_traits::DataType< ::tum_alle_common_msgs::srvInferFromList > 
template<>
struct DataType< ::tum_alle_common_msgs::srvInferFromListResponse>
{
  static const char* value()
  {
    return DataType< ::tum_alle_common_msgs::srvInferFromList >::value();
  }
  static const char* value(const ::tum_alle_common_msgs::srvInferFromListResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TUM_ALLE_COMMON_MSGS_MESSAGE_SRVINFERFROMLIST_H
