// Generated by gencpp from file tum_alle_common_msgs/srvStartPlanner.msg
// DO NOT EDIT!


#ifndef TUM_ALLE_COMMON_MSGS_MESSAGE_SRVSTARTPLANNER_H
#define TUM_ALLE_COMMON_MSGS_MESSAGE_SRVSTARTPLANNER_H

#include <ros/service_traits.h>


#include <tum_alle_common_msgs/srvStartPlannerRequest.h>
#include <tum_alle_common_msgs/srvStartPlannerResponse.h>


namespace tum_alle_common_msgs
{

struct srvStartPlanner
{

typedef srvStartPlannerRequest Request;
typedef srvStartPlannerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct srvStartPlanner
} // namespace tum_alle_common_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tum_alle_common_msgs::srvStartPlanner > {
  static const char* value()
  {
    return "51488b07d0aacb6956a0af72c8f1d91b";
  }

  static const char* value(const ::tum_alle_common_msgs::srvStartPlanner&) { return value(); }
};

template<>
struct DataType< ::tum_alle_common_msgs::srvStartPlanner > {
  static const char* value()
  {
    return "tum_alle_common_msgs/srvStartPlanner";
  }

  static const char* value(const ::tum_alle_common_msgs::srvStartPlanner&) { return value(); }
};


// service_traits::MD5Sum< ::tum_alle_common_msgs::srvStartPlannerRequest> should match 
// service_traits::MD5Sum< ::tum_alle_common_msgs::srvStartPlanner > 
template<>
struct MD5Sum< ::tum_alle_common_msgs::srvStartPlannerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tum_alle_common_msgs::srvStartPlanner >::value();
  }
  static const char* value(const ::tum_alle_common_msgs::srvStartPlannerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tum_alle_common_msgs::srvStartPlannerRequest> should match 
// service_traits::DataType< ::tum_alle_common_msgs::srvStartPlanner > 
template<>
struct DataType< ::tum_alle_common_msgs::srvStartPlannerRequest>
{
  static const char* value()
  {
    return DataType< ::tum_alle_common_msgs::srvStartPlanner >::value();
  }
  static const char* value(const ::tum_alle_common_msgs::srvStartPlannerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tum_alle_common_msgs::srvStartPlannerResponse> should match 
// service_traits::MD5Sum< ::tum_alle_common_msgs::srvStartPlanner > 
template<>
struct MD5Sum< ::tum_alle_common_msgs::srvStartPlannerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tum_alle_common_msgs::srvStartPlanner >::value();
  }
  static const char* value(const ::tum_alle_common_msgs::srvStartPlannerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tum_alle_common_msgs::srvStartPlannerResponse> should match 
// service_traits::DataType< ::tum_alle_common_msgs::srvStartPlanner > 
template<>
struct DataType< ::tum_alle_common_msgs::srvStartPlannerResponse>
{
  static const char* value()
  {
    return DataType< ::tum_alle_common_msgs::srvStartPlanner >::value();
  }
  static const char* value(const ::tum_alle_common_msgs::srvStartPlannerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TUM_ALLE_COMMON_MSGS_MESSAGE_SRVSTARTPLANNER_H
