// Generated by gencpp from file tum_alle_common_msgs/srvStableObjects.msg
// DO NOT EDIT!


#ifndef TUM_ALLE_COMMON_MSGS_MESSAGE_SRVSTABLEOBJECTS_H
#define TUM_ALLE_COMMON_MSGS_MESSAGE_SRVSTABLEOBJECTS_H

#include <ros/service_traits.h>


#include <tum_alle_common_msgs/srvStableObjectsRequest.h>
#include <tum_alle_common_msgs/srvStableObjectsResponse.h>


namespace tum_alle_common_msgs
{

struct srvStableObjects
{

typedef srvStableObjectsRequest Request;
typedef srvStableObjectsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct srvStableObjects
} // namespace tum_alle_common_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tum_alle_common_msgs::srvStableObjects > {
  static const char* value()
  {
    return "66f13e3d3ec3200b333a36dc56ae0cc3";
  }

  static const char* value(const ::tum_alle_common_msgs::srvStableObjects&) { return value(); }
};

template<>
struct DataType< ::tum_alle_common_msgs::srvStableObjects > {
  static const char* value()
  {
    return "tum_alle_common_msgs/srvStableObjects";
  }

  static const char* value(const ::tum_alle_common_msgs::srvStableObjects&) { return value(); }
};


// service_traits::MD5Sum< ::tum_alle_common_msgs::srvStableObjectsRequest> should match 
// service_traits::MD5Sum< ::tum_alle_common_msgs::srvStableObjects > 
template<>
struct MD5Sum< ::tum_alle_common_msgs::srvStableObjectsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tum_alle_common_msgs::srvStableObjects >::value();
  }
  static const char* value(const ::tum_alle_common_msgs::srvStableObjectsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tum_alle_common_msgs::srvStableObjectsRequest> should match 
// service_traits::DataType< ::tum_alle_common_msgs::srvStableObjects > 
template<>
struct DataType< ::tum_alle_common_msgs::srvStableObjectsRequest>
{
  static const char* value()
  {
    return DataType< ::tum_alle_common_msgs::srvStableObjects >::value();
  }
  static const char* value(const ::tum_alle_common_msgs::srvStableObjectsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tum_alle_common_msgs::srvStableObjectsResponse> should match 
// service_traits::MD5Sum< ::tum_alle_common_msgs::srvStableObjects > 
template<>
struct MD5Sum< ::tum_alle_common_msgs::srvStableObjectsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tum_alle_common_msgs::srvStableObjects >::value();
  }
  static const char* value(const ::tum_alle_common_msgs::srvStableObjectsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tum_alle_common_msgs::srvStableObjectsResponse> should match 
// service_traits::DataType< ::tum_alle_common_msgs::srvStableObjects > 
template<>
struct DataType< ::tum_alle_common_msgs::srvStableObjectsResponse>
{
  static const char* value()
  {
    return DataType< ::tum_alle_common_msgs::srvStableObjects >::value();
  }
  static const char* value(const ::tum_alle_common_msgs::srvStableObjectsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TUM_ALLE_COMMON_MSGS_MESSAGE_SRVSTABLEOBJECTS_H
