// Generated by gencpp from file tum_alle_common_msgs/srvUpdateClusters.msg
// DO NOT EDIT!


#ifndef TUM_ALLE_COMMON_MSGS_MESSAGE_SRVUPDATECLUSTERS_H
#define TUM_ALLE_COMMON_MSGS_MESSAGE_SRVUPDATECLUSTERS_H

#include <ros/service_traits.h>


#include <tum_alle_common_msgs/srvUpdateClustersRequest.h>
#include <tum_alle_common_msgs/srvUpdateClustersResponse.h>


namespace tum_alle_common_msgs
{

struct srvUpdateClusters
{

typedef srvUpdateClustersRequest Request;
typedef srvUpdateClustersResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct srvUpdateClusters
} // namespace tum_alle_common_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tum_alle_common_msgs::srvUpdateClusters > {
  static const char* value()
  {
    return "93a02a6f845c7e0038a223d54e7006b7";
  }

  static const char* value(const ::tum_alle_common_msgs::srvUpdateClusters&) { return value(); }
};

template<>
struct DataType< ::tum_alle_common_msgs::srvUpdateClusters > {
  static const char* value()
  {
    return "tum_alle_common_msgs/srvUpdateClusters";
  }

  static const char* value(const ::tum_alle_common_msgs::srvUpdateClusters&) { return value(); }
};


// service_traits::MD5Sum< ::tum_alle_common_msgs::srvUpdateClustersRequest> should match 
// service_traits::MD5Sum< ::tum_alle_common_msgs::srvUpdateClusters > 
template<>
struct MD5Sum< ::tum_alle_common_msgs::srvUpdateClustersRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tum_alle_common_msgs::srvUpdateClusters >::value();
  }
  static const char* value(const ::tum_alle_common_msgs::srvUpdateClustersRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tum_alle_common_msgs::srvUpdateClustersRequest> should match 
// service_traits::DataType< ::tum_alle_common_msgs::srvUpdateClusters > 
template<>
struct DataType< ::tum_alle_common_msgs::srvUpdateClustersRequest>
{
  static const char* value()
  {
    return DataType< ::tum_alle_common_msgs::srvUpdateClusters >::value();
  }
  static const char* value(const ::tum_alle_common_msgs::srvUpdateClustersRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tum_alle_common_msgs::srvUpdateClustersResponse> should match 
// service_traits::MD5Sum< ::tum_alle_common_msgs::srvUpdateClusters > 
template<>
struct MD5Sum< ::tum_alle_common_msgs::srvUpdateClustersResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tum_alle_common_msgs::srvUpdateClusters >::value();
  }
  static const char* value(const ::tum_alle_common_msgs::srvUpdateClustersResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tum_alle_common_msgs::srvUpdateClustersResponse> should match 
// service_traits::DataType< ::tum_alle_common_msgs::srvUpdateClusters > 
template<>
struct DataType< ::tum_alle_common_msgs::srvUpdateClustersResponse>
{
  static const char* value()
  {
    return DataType< ::tum_alle_common_msgs::srvUpdateClusters >::value();
  }
  static const char* value(const ::tum_alle_common_msgs::srvUpdateClustersResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TUM_ALLE_COMMON_MSGS_MESSAGE_SRVUPDATECLUSTERS_H
